apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: bank

spec:
  serviceName: kafka
  replicas: 1

  selector:
    matchLabels:
      app: kafka

  template:
    metadata:
      labels:
        app: kafka

    spec:
      # Prevent Kubernetes injecting KAFKA_PORT
      enableServiceLinks: false

      # Allow Kafka (GID 1000) to write to the PVC
      securityContext:
        fsGroup: 1000

      containers:
        - name: kafka
          image: confluentinc/cp-kafka:8.1.1

          ports:
            - name: broker
              containerPort: 29092

            - name: controller
              containerPort: 29093

          env:
            # -------------------------
            # KRaft
            # -------------------------

            # ID of this Kafka node
            - name: KAFKA_NODE_ID
              value: "1"

            # This node acts as both broker + controller
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"

            # -------------------------
            # Listeners
            # -------------------------

            # Listen locally inside the pod
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093"

            # Other pods connect through the Kafka Service
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:29092"

            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"

            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"

            # -------------------------
            # KRaft controller
            # -------------------------

            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"

            # Single controller is inside this same pod
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:29093"

            # -------------------------
            # Single-node Kafka
            # -------------------------

            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"

            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"

            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"

            # -------------------------
            # Storage
            # -------------------------

            - name: KAFKA_LOG_DIRS
              value: "/mnt/kafka/data"

            # ID used to format the KRaft storage
            - name: CLUSTER_ID
              value: "MkU3OEVBNTcwNTJENDM2Qk"

          volumeMounts:
            - name: kafka-data
              mountPath: /mnt/kafka

  # -------------------------
  # Persistent EBS storage
  # -------------------------

  volumeClaimTemplates:
    - metadata:
        name: kafka-data

      spec:
        accessModes:
          - ReadWriteOnce

        storageClassName: gp2

        resources:
          requests:
            storage: 10Gi
