apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-secrets
  namespace: bank
spec:
  provider: aws
  parameters:
    region: eu-west-2
    usePodIdentity: "true"
    objects: |
      - objectName: "banking-app/database"
        objectType: "secretsmanager"
        jmesPath:
          - path: "POSTGRES_USER"
            objectAlias: "POSTGRES_USER"
          - path: "POSTGRES_PASSWORD"
            objectAlias: "POSTGRES_PASSWORD"
          - path: "POSTGRES_DB"
            objectAlias: "POSTGRES_DB"
